name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate repo structure
        run: |
          test -d deploy && test -d oac && test -d apps && echo "OK"
